[workspace]
members = [
  "crates/libs/lib-proxy-config",
  "crates/libs/lib-proxy",
  "crates/services/proxy",
]
resolver = "3"

[workspace.package]
version = "0.0.1"
description = ""
authors = ["Zenno Zenith <95485961+ZennoZenith@users.noreply.github.com>"]
license = "GNU AGPLv3"
edition = "2024"
repository = "https://github.com/ZennoZenith/proxy-manager"
keywords = ["proxy-manager"]
# rust-version = "1.92"

[workspace.lints.rust]
unsafe_code = "forbid"
# unused = { level = "allow", priority = -1 } # For exploratory dev.


[workspace.dependencies]
clap = { version = "4.5", features = ["derive"] }
thiserror = "2"
color-eyre = "0.6"
# miette = { version = "7.6.0", features = ["fancy"] }
serde = { version = "1", features = ["derive", "rc"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

http = "1"
chrono = "0.4"
time = { version = "0.3", features = ["formatting", "parsing", "serde"] }
strum = "0.28"
strum_macros = "0.28"
url = { version = "2", features = ["serde"] }
uuid = { version = "1", features = ["v4", "fast-rng"] }

# axum = { version = "0.8", features = ["macros", "ws"] }
# sqlx = { version = "0.8", features = [
#   "macros",
#   "runtime-tokio",
#   "postgres",
#   "uuid",
#   "time",
#   "chrono",
#   "bigdecimal",
#   "bit-vec",
# ] }
# serde_json = "1"
# serde_with = { version = "3", features = ["time_0_3"] }
# tower = "0.5"
# tokio = { version = "1", features = ["full"] }
# tower-cookies = "0.11"
# tower-http = { version = "0.6", features = ["fs"] }
