[workspace]
members = [
  "crates/libs/lib-auth",
  "crates/libs/lib-config",
  "crates/libs/lib-proxy",
  "crates/libs/lib-pingora-proxy",
  # "crates/libs/lib-angie-proxy",
  "crates/libs/lib-utils",
  "crates/libs/lib-web",
  "crates/services/proxy",
]
resolver = "3"

[workspace.package]
version = "0.0.1"
description = ""
authors = ["Zenno Zenith <95485961+ZennoZenith@users.noreply.github.com>"]
license = "GNU AGPLv3"
edition = "2024"
repository = "https://github.com/ZennoZenith/proxy-manager"
# rust-version = "1.92"

[workspace.lints.rust]
unsafe_code = "forbid"
# unused = { level = "allow", priority = -1 } # For exploratory dev.


[workspace.dependencies]
async-trait = "0.1"
http = "1"
toml = "0.9"
axum = { version = "0.8", features = ["macros", "ws"] }
chrono = "0.4"
time = { version = "0.3", features = ["formatting", "parsing", "serde"] }
color-eyre = "0.6"
sqlx = { version = "0.8", features = [
  "macros",
  "runtime-tokio",
  "postgres",
  "uuid",
  "time",
  "chrono",
  "bigdecimal",
  "bit-vec",
] }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
serde_with = { version = "3", features = ["time_0_3"] }
strum = "0.27"
strum_macros = "0.27"
thiserror = "2"
tower = "0.5"
tokio = { version = "1", features = ["full"] }
tower-cookies = "0.11"
tower-http = { version = "0.6", features = ["fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1", features = ["v4", "fast-rng"] }
url = { version = "2", features = ["serde"] }
miette = { version = "7.6.0", features = ["fancy"] }
