[package]
name = "lib-proxy"
version.workspace = true
description.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
lib-proxy-config = { path = "../../libs/lib-proxy-config" }

async-trait = "0.1"
bytes = "1"
futures = "0.3"
pingora = { version = "0.7", features = ["cache", "lb", "openssl", "proxy"] }

http = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]

[features]
default = []
