[[server]]
enable = true
name = ["abc.zennozenith.com"]

[server.listen.http]
port = [6188]
# port = [8080]

[server.proxy]
alg = "RoundRobin"
type = "LoadBalancer"

[[server.proxy.backend]]
scheme.type = "https"
scheme.sni = "example.com"
address = "127.0.0.1:4004"
weight = 2

[[server.proxy.backend]]
scheme.type = "http"
address = "127.0.0.1:4000"
weight = 1

[[server.proxy.backend]]
scheme.type = "http"
address = "127.0.0.1:4001"
weight = 1

[[server.proxy.backend]]
scheme.type = "http"
address = "127.0.0.1:4002"
weight = 1

[[server]]
enable = true
name = ["pqr.zennozenith.com"]

[server.listen.http]
port = [6188]
# port = [8080]

[server.listen.https]
# port = [8443]
port = [6189]
http2 = true
ssl_certificate = "examples/keys/pqr.zennozenith.com/server.crt"
ssl_certificate_key = "examples/keys/pqr.zennozenith.com/key.pem"

[server.proxy]
type = "Proxy"
scheme.type = "http"
address = "127.0.0.1:4000"
