[error_page]
"default" = "examples/html/default.html"
"400" = "examples/html/400.html"
"403" = "examples/html/403.html"
"404" = "examples/html/404.html"
"500" = "examples/html/500.html"
"502" = "examples/html/502.html"
"503" = "examples/html/503.html"
"504" = "examples/html/504.html"

[[server]]
enable = true
name = ["ccc.zennozenith.com"]

[server.listen.http]
port = [6188]

[server.kind.custom]
http_code = 200
content = "Hello"
# content = [72, 101, 108, 108, 111]  ## "Hello" as ASCII bytes
headers = { "X-Test" = "TEST", "Content-Type" = "text/plain" }

[[server]]
enable = true
name = ["bbb.zennozenith.com"]

[server.listen.http]
port = [6188]

[server.kind.custom]
http_code = 200
headers = { "X-Test" = "TEST", "Content-Type" = "text/html" }

[server.kind.custom.content]
path = "./Hello"
cache = true

[[server]]
enable = true
name = ["xyz.zennozenith.com"]

[server.listen.http]
port = [6188]

[server.kind.redirect]
http_code = 307
preserve_path = true
location = "https://pqr.zennozenith.com"

[[server]]
name = ["no.zennozenith.com"]

[server.listen.http]
port = [6188]

[server.kind.proxy.direct]
address = "127.0.0.1:9999"
scheme.protocol = "http"

[[server]]
enable = true
name = ["pqr.zennozenith.com"]

[server.listen.http]
port = [6188]

[server.listen.https]
port = [6189]
http2 = true
ssl_certificate = "examples/keys/pqr.zennozenith.com/server.crt"
ssl_certificate_key = "examples/keys/pqr.zennozenith.com/key.pem"

[server.kind.proxy.direct]
address = "127.0.0.1:4004"
scheme = { protocol = "https", sni = "pqr.zennozenith.com" }

[[server]]
enable = true
name = ["abc.zennozenith.com", "aaa.zennozenith.com"]

[server.listen.http]
port = [6188]

[server.kind.proxy.loadbalanced]
alg = "RoundRobin"

[[server.kind.proxy.loadbalanced.backend]]
scheme.protocol = "https"
scheme.sni = "example.com"
address = "127.0.0.1:4004"
weight = 2

[[server.kind.proxy.loadbalanced.backend]]
scheme.protocol = "http"
address = "127.0.0.1:4000"

[[server.kind.proxy.loadbalanced.backend]]
scheme.protocol = "http"
address = "127.0.0.1:4001"

[[server.kind.proxy.loadbalanced.backend]]
scheme.protocol = "http"
address = "127.0.0.1:4002"
weight = 1
