[package]
name = "lib-pingora-proxy"
version.workspace = true
description.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
# rust-version.workspace = true
readme = "README.md"
# keywords = ["proxy-manager"]

[dependencies]
pingora = { version = "0.7", features = ["cache", "lb", "openssl", "proxy"] }
futures = "0.3"
async-trait = { workspace = true }
http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
url = { workspace = true }
color-eyre = { workspace = true }
thiserror = { workspace = true }
lib-config = { path = "../../libs/lib-config" }

# [[example]]
# name = "example1"

[dev-dependencies]

[features]
default = []
